name: Feature Request
description: Suggest an idea for this project
title: '[feat]: '
labels: ['enhancement']
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: feature
    attributes:
      label: Describe the Feature Request
      description: A clear and concise description of what the feature request is. Please include if your feature request is related to a problem.
      placeholder: My amazing idea is...
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe Preferred Solution
      description: A clear and concise description of what you want to happen.
      placeholder: This could be accomplished by...
    validations:
      required: false
  - type: textarea
    id: proposed-alternative
    attributes:
      label: Describe Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: What if...
    validations:
      required: false
  - type: textarea
    id: code
    attributes:
      label: Related Code
      description: If you are able to illustrate the bug or feature request with an example or pseudo code, please provide it here.
      render: js
  - type: textarea
    id: extra-context
    attributes:
      label: Additional Context
      description: List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to add, use case, Stack Overflow links, forum links, screenshots, OS if applicable, etc.
    validations:
      required: false
  - type: dropdown
    id: would-pr
    attributes:
      label: If the feature request is approved, would you be willing to submit a PR?
      description: Help can be provided if you need assistance submitting a PR
      multiple: false
      options:
        - Yes
        - No
    validations:
      required: true
